spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      database: simpletestdb
      port: 27017
      host: localhost
logging:
  level:
    ROOT: INFO